PluginName: TestChat
Admin:
  Permission: premierchat.admin
PluginPrefix: TC
Prefixes:
  Default:
    prefix: Hi
Channels:
  OnlineChannels: 
    - Global
    - Local
  DefaultChannel: Global
  Global:
    format: Global 
    type: GLOBAL
  Local:
    format: Local 
    type: LOCAL
    range: 100