name: PremierChat
version: 0.9
author: AstramG
main: me.AstramG.PremierChat.main.PremierChat
commands:
  pc:
    usage: /pc <args...>
    description: The base command for PremierChat!
  uuid:
    usage: /uuid <player>
    description: Shows the UUID of the player!