name: PremierChat
version: 1.0
author: AstramG
main: me.AstramG.PremierChat.main.PremierChat
commands:
  pc:
    usage: /pc <args...>
    description: The base command for PremierChat!
  uuid:
    usage: /uuid <player>
    description: Shows the UUID of the player!
  msg:
    usage: /msg <player> <msg>
    description: Messages the player with the message!
  r:
    usage: /r <msg>
    usage: Replies to the last person spoken to!