PluginName: TestChat
PluginPrefix: TC
Channels:
  OnlineChannels: Global, Local
  DefaultChannel: Global
  Global:
    format: &7[&2Global&7] &6%name% &7->&f 
    type: GLOBAL
  Local:
    format: &7[&4Local&7] &6%name% &7->&f 
    type: LOCAL
    range: 100